services:
  - type: web
    name: swift-ride-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: mongodb+srv://ngozobolwanengolobane_db_user:2022gogo@cluster0.2xj7xle.mongodb.net/delivery_app?retryWrites=true&w=majority
        sync: false
      - key: 2022gogo
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true